jupyterhub:
  hub:
    db:
      pvc:
        # This gonna store logs
        storage: 10Gi
    config:
      GoogleOAuthenticator:
        oauth_callback_url: "https://utoronto.2i2c.cloud/hub/oauth_callback"
  scheduling:
    userPlaceholder:
      replicas: 100
  proxy:
    https:
      hosts:
      - utoronto.2i2c.cloud
      - jupyter.utoronto.ca
