jupyterhub:
  auth:
    google:
      callbackUrl: "https://staging.utoronto.2i2c.cloud/hub/oauth_callback"
  proxy:
    https:
      hosts:
      - staging.utoronto.2i2c.cloud
  scheduling:
    userPlaceholder:
      replicas: 5

  prePuller:
    continuous:
      # Don't need continuous pre-puller on staging
      enabled: false
